language: php
php:
  - '7.1'
  - '7.2'
  - nightly
  
install:
  - sudo add-apt-repository ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - sudo apt-get -y install gearman-job-server php-gearman

before_script:
  - "composer install"
